### ISSUE TITLE
Error while installing Jamspell on Python3.7

### ISSUE THREAD

**Issue by Mozhdeh-d** [bakwc/JamSpell#41]
Hi,
I'm trying to install Jamspell, but an AssertionError occurs after running 'assert swigBinary is not None' and the following error appears:

`Command "c:\users\mozhdeh\appdata\local\programs\python\python37\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Mozhdeh\\AppData\\Local\\Temp\\pip-install-yeklct7v\\jamspell\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Mozhdeh\AppData\Local\Temp\pip-record-somxdjnu\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Mozhdeh\AppData\Local\Temp\pip-install-yeklct7v\jamspell\`

I also tried to install it on python2 and 3.6, but the same error occured.

Would you please help me? I'm very eager to use JamSpell in my project.
Thanks in advance :)

**Comment by bakwc** [comment]
You need to install swig first.

**Comment by basque21** [comment]
i have installed it (`sudo apt-get install swig3.0`, no problems) and still the same error

**Comment by valdrinshala** [comment]
Can somebody help? What is missing?

Exception:
Traceback (most recent call last):
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 118: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 118: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_set.py", line 729, in cleanup_files
    req.remove_temporary_source()
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_install.py", line 977, in remove_temporary_source
    rmtree(self.source_dir)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\shutil.py", line 376, in _rmtree_unsafe
    onerror(os.listdir, path, sys.exc_info())
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 112, in rmtree_errorhandler
    os.chmod(path, stat.S_IWRITE)
PermissionError: [WinError 5] Zugriff verweigert: 'C:\\Users\\VShala\\AppData\\Local\\Temp\\pip-build-r5j3cnpy\\jamspell\\contrib\\cityhash'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\commands\install.py", line 385, in run
    requirement_set.cleanup_files()
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\utils\build.py", line 38, in __exit__
    self.cleanup()
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\utils\build.py", line 42, in cleanup
    rmtree(self.name)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\retrying.py", line 212, in call
    raise attempt.get()
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\six.py", line 686, in reraise
    raise value
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\_vendor\retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\shutil.py", line 494, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\shutil.py", line 384, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\shutil.py", line 376, in _rmtree_unsafe
    onerror(os.listdir, path, sys.exc_info())
  File "c:\users\vshala\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 112, in rmtree_errorhandler
    os.chmod(path, stat.S_IWRITE)
PermissionError: [WinError 5] Zugriff verweigert: 'C:\\Users\\VShala\\AppData\\Local\\Temp\\pip-build-r5j3cnpy\\jamspell\\contrib\\cityhash'

**Comment by pratap-is-here** [comment]
Jamspell is supported in Python 2.7 only. Try Symspell here: [https://pypi.org/project/symspellpy/](url)

**Comment by IgorSondors** [comment]
Hello, can someone help? I installed swig, but can not install jamspell via pip

(pip_tf) sonders@pc-sonders:~$ swig -version

SWIG Version 3.0.12

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information

**Comment by IgorSondors** [comment]
(pip_tf) sonders@pc-sonders:~$ pip install jamspell
Collecting jamspell
  Using cached jamspell-0.0.11.tar.gz (60 kB)
Building wheels for collected packages: jamspell
  Building wheel for jamspell (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/sonders/anaconda3/envs/pip_tf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sbuf87uy/jamspell/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sbuf87uy/jamspell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-o1_55tr1
       cwd: /tmp/pip-install-sbuf87uy/jamspell/
  Complete output (15 lines):
  running bdist_wheel
  running build
  running build_ext
  building '_jamspell' extension
  swigging jamspell.i to jamspell_wrap.cpp
  /usr/bin/swig3.0 -python -c++ -o jamspell_wrap.cpp jamspell.i
  creating build
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/jamspell
  creating build/temp.linux-x86_64-3.7/contrib
  creating build/temp.linux-x86_64-3.7/contrib/cityhash
  creating build/temp.linux-x86_64-3.7/contrib/phf
  gcc -pthread -B /home/sonders/anaconda3/envs/pip_tf/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I. -Ijamspell -I/home/sonders/anaconda3/envs/pip_tf/include/python3.7m -c jamspell/lang_model.cpp -o build/temp.linux-x86_64-3.7/jamspell/lang_model.o -std=c++11 -O2
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for jamspell
  Running setup.py clean for jamspell
Failed to build jamspell
Installing collected packages: jamspell
    Running setup.py install for jamspell ... error
    ERROR: Command errored out with exit status 1:
     command: /home/sonders/anaconda3/envs/pip_tf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sbuf87uy/jamspell/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sbuf87uy/jamspell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jglc9lwu/install-record.txt --single-version-externally-managed --compile --install-headers /home/sonders/anaconda3/envs/pip_tf/include/python3.7m/jamspell
         cwd: /tmp/pip-install-sbuf87uy/jamspell/
    Complete output (14 lines):
    running install
    running build_ext
    building '_jamspell' extension
    swigging jamspell.i to jamspell_wrap.cpp
    /usr/bin/swig3.0 -python -c++ -o jamspell_wrap.cpp jamspell.i
    creating build
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/jamspell
    creating build/temp.linux-x86_64-3.7/contrib
    creating build/temp.linux-x86_64-3.7/contrib/cityhash
    creating build/temp.linux-x86_64-3.7/contrib/phf
    gcc -pthread -B /home/sonders/anaconda3/envs/pip_tf/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I. -Ijamspell -I/home/sonders/anaconda3/envs/pip_tf/include/python3.7m -c jamspell/lang_model.cpp -o build/temp.linux-x86_64-3.7/jamspell/lang_model.o -std=c++11 -O2
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/sonders/anaconda3/envs/pip_tf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-sbuf87uy/jamspell/setup.py'"'"'; __file__='"'"'/tmp/pip-install-sbuf87uy/jamspell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jglc9lwu/install-record.txt --single-version-externally-managed --compile --install-headers /home/sonders/anaconda3/envs/pip_tf/include/python3.7m/jamspell Check the logs for full command output.

**Comment by Shridharpawar77** [comment]
Hi Guys did anyone solved above issue. I have install the swig==3.0.12 and yet gcc fails to install jamspell
