### ISSUE TITLE
assert subprocess.check_output([swigBinary, "-version"]).find(b'SWIG Version 3') != -1     AssertionError

### ISSUE THREAD

**Issue by aiainui** [bakwc/JamSpell#78]
Hi! Everyone. I have installed it swig/3.0.12. pip install jamspell----getting this error:

Collecting jamspell
  Using cached https://files.pythonhosted.org/packages/5a/16/0a808e926a835604007066085cb2183b337694a06240a99945b31fa14f27/jamspell-0.0.11.tar.gz
Building wheels for collected packages: jamspell
  Building wheel for jamspell (setup.py) ... error
  ERROR: Complete output from command /home/dengyulong/myproject/py3/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-rwh2wdws/jamspell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-dhu042uh --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  running build_ext
  building '_jamspell' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-rwh2wdws/jamspell/setup.py", line 73, in <module>
      include_package_data=True,
    File "/home/dengyulong/myproject/py3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Python3.6/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Python3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/Python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/dengyulong/myproject/py3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 202, in run
      self.run_command('build')
    File "/usr/local/Python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-rwh2wdws/jamspell/setup.py", line 33, in run
      self.run_command('build_ext')
    File "/usr/local/Python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/Python3.6/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/local/Python3.6/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/local/Python3.6/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/usr/local/Python3.6/lib/python3.6/distutils/command/build_ext.py", line 505, in build_extension
      sources = self.swig_sources(sources, ext)
    File "/usr/local/Python3.6/lib/python3.6/distutils/command/build_ext.py", line 596, in swig_sources
      swig = self.swig or self.find_swig()
    File "/tmp/pip-install-rwh2wdws/jamspell/setup.py", line 46, in find_swig
      assert subprocess.check_output([swigBinary, "-version"]).find(b'SWIG Version 3') != -1
  AssertionError
  ----------------------------------------
  ERROR: Failed building wheel for jamspell
  Running setup.py clean for jamspell
Failed to build jamspell
Installing collected packages: jamspell
  Running setup.py install for jamspell ... error
    ERROR: Complete output from command /home/dengyulong/myproject/py3/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-rwh2wdws/jamspell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j1nh9oli/install-record.txt --single-version-externally-managed --compile --install-headers /home/dengyulong/myproject/py3/include/site/python3.6/jamspell:
    ERROR: running install
    running build_ext
    building '_jamspell' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rwh2wdws/jamspell/setup.py", line 73, in <module>
        include_package_data=True,
      File "/home/dengyulong/myproject/py3/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Python3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Python3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-rwh2wdws/jamspell/setup.py", line 39, in run
        self.run_command('build_ext')
      File "/usr/local/Python3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Python3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/Python3.6/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/local/Python3.6/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/Python3.6/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/local/Python3.6/lib/python3.6/distutils/command/build_ext.py", line 505, in build_extension
        sources = self.swig_sources(sources, ext)
      File "/usr/local/Python3.6/lib/python3.6/distutils/command/build_ext.py", line 596, in swig_sources
        swig = self.swig or self.find_swig()
      File "/tmp/pip-install-rwh2wdws/jamspell/setup.py", line 46, in find_swig
        assert subprocess.check_output([swigBinary, "-version"]).find(b'SWIG Version 3') != -1
    AssertionError
    ----------------------------------------
ERROR: Command "/home/dengyulong/myproject/py3/bin/python3.6 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-rwh2wdws/jamspell/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-j1nh9oli/install-record.txt --single-version-externally-managed --compile --install-headers /home/dengyulong/myproject/py3/include/site/python3.6/jamspell" failed with error code 1 in /tmp/pip-install-rwh2wdws/jamspell/

**Comment by VJAYSLN** [comment]
I am also getting same error..

**Comment by bakwc** [comment]
You need a `swig3` to install JamSpell. More clear instructions and priority support provided in `JamSpellPro`.

JamSpellPro is available at [jamspell.com](https://jamspell.com/)
